image: alpine/latest
packages:
  - nodejs
  - npm
  - shellcheck
sources:
  - https://git.sr.ht/~rasch/transfer
environment:
  project: transfer
secrets:
  - ac7323fc-d1fd-4005-97fb-a8c058a0dc6f # NPM publish token
tasks:
  - lint: |
      cd "$project"
      shellcheck transfer.sh
  - stop_if_not_release: |
      cd "$project"
      git describe --exact-match HEAD || complete-build
  - release: |
      cd "$project"
      echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' >> .npmrc
      set +x
      . ~/.env
      set -x
      npm publish --access public
