image: alpine/latest
packages:
  - nodejs
  - npm
  - shellcheck
sources:
  - https://git.sr.ht/~rasch/transfer
environment:
  project: transfer
secrets:
  - 2b8f0d2a-cab9-451d-b684-6b89582fb7b0 # NPM publish token
tasks:
  - lint: |
      cd "$project"
      shellcheck transfer.sh
  - stop_if_not_release: |
      cd "$project"
      git describe --exact-match HEAD || complete-build
  - release: |
      cd "$project"
      echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' >> .npmrc
      set +x
      . ~/.env
      set -x
      npm publish --access public
